//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientInterest
    {
        public string ID { get; set; }
        public string userName { get; set; }
        public string interest { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Interest Interest1 { get; set; }
    }
}
