//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public int locationID { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string country { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
    }
}
