//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessage
    {
        public int Id { get; set; }
        public string sender { get; set; }
        public string receiver { get; set; }
        public string messageBody { get; set; }
        public string senderProfile { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<bool> @new { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
